/*   
 *  Copyright (C) 2011- 2018 Rao Youkun(960747373@qq.com)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 */

/*
 * Warning:
 * Do not edit this file!
 */
#ifndef  __LGUI_DEP_CNF_BASIC_HEADER__
#define  __LGUI_DEP_CNF_BASIC_HEADER__


/* Single-version support macro */
#undef  _LG_ALONE_VERSION_
#ifndef  _LG_MULTI_THREAD_
#define  _LG_ALONE_VERSION_
#endif  /* _LG_MULTI_THREAD_ */


/* Color support macro */
#ifndef  _LG_COLOR_
    #undef  _LG_1_BIT_COLOR_
    #undef  _LG_2_BIT_COLOR_
    #undef  _LG_4_BIT_COLOR_
    #undef  _LG_8_BIT_COLOR_
    #undef  _LG_15_BIT_COLOR_
    #undef  _LG_16_BIT_COLOR_
    #undef  _LG_24_BIT_COLOR_
    #undef  _LG_32_BIT_COLOR_

    #undef  _LG_COMMON_PALETTE_

    #undef  _LG_PALETTE_ROUTINE_

    #undef  _LG_COLOR_CONVERSION_
#endif  /* _LG_COLOR_ */
    
#ifndef  _LG_PALETTE_ROUTINE_    
    #undef  _LG_8_BIT_SYSTEM_PALETTE_
#endif  /* _LG_PALETTE_ROUTINE_ */


#ifdef  _LG_PALETTE_COLOR_CONVERSION_    
#ifndef  _LG_PALETTE_ROUTINE_
#define  _LG_PALETTE_ROUTINE_
#endif  /* _LG_PALETTE_ROUTINE_ */
#endif  /* _LG_PALETTE_COLOR_CONVERSION_ */


/* DC support macro */
#ifndef  _LG_DC_
    #undef  _LG_PEN_
    #undef  _LG_BRUSH_
    #undef  _LG_2D_
    #undef  _LG_FONT_
    #undef  _LG_TEXT_METRIC_
    #undef  _LG_TEXT_OUT_EXTENSION_
    #undef  _LG_TEXT_GLYPH_
    #undef  _LG_BITMAP_
    #undef  _LG_ICON_
    #undef  _LG_GIF_
#endif   /* _LG_DC_ */
 
#ifndef  _LG_2D_
    #undef  _LG_LINE_
    #undef  _LG_RECTANGLE_
    #undef  _LG_ELLIPSE_
#endif  /* _LG_2D_ */

#ifndef  _LG_FONT_
    #undef  _LG_MONO_CHARSET_FONT_
    #undef  _LG_MONO_DISCRETE_FONT_
    #undef  _LG_MIXED_CHARSET_FONT_
    #undef  _LG_MIXED_DISCRETE_FONT_

    #undef  _LG_FONT_ID_

    #undef  _LG_ASCII_LATIN_D0816C_FONT_
    #undef  _LG_ASCII_LATIN_D0612C_FONT_

    #undef  _LG_MULTI_BYTE_CODE_VERSION_
        #undef  _LG_GB2312_D1616CS_C1_FONT_
            #undef  INCLUDE_GB2312_D1616CS_SYSBOL
            #undef  INCLUDE_GB2312_D1616CS_C2

        #undef  _LG_GB2312_D1212CS_C1_FONT_
            #undef  INCLUDE_GB2312_D1212CS_SYSBOL
            #undef  INCLUDE_GB2312_D1212CS_C2

    #undef  _LG_UNICODE_VERSION_
        #undef   _LG_UNICODE_BIG_ENDIAN_

        #undef  _LG_CJK_UNIFIED_D1616CS_FONT_
        #undef  _LG_HZ1616_PUNCTUATION_

        #undef  _LG_CJK_UNIFIED_D1212CS_FONT_
        #undef  _LG_HZ1212_PUNCTUATION_
#endif  /* _LG_FONT_ */

#ifdef  _LG_MULTI_BYTE_CODE_VERSION_
    #undef  _LG_UNICODE_VERSION_
        #undef   _LG_UNICODE_BIG_ENDIAN_

        #undef  _LG_CJK_UNIFIED_D1616CS_FONT_
        #undef  _LG_HZ1616_PUNCTUATION_

        #undef  _LG_CJK_UNIFIED_D1212CS_FONT_
        #undef  _LG_HZ1212_PUNCTUATION_
#endif /* _LG_MULTI_BYTE_CODE_VERSION_ */

#ifdef  _LG_DC_
    #ifndef  MAX_DC_NUM
        #define  MAX_DC_NUM                                     5
    #endif  /* MAX_DC_NUM */

    #if  (MAX_DC_NUM<1)?1:0
        #undef   MAX_DC_NUM
        #define  MAX_DC_NUM                                     1
    #endif
#endif  /* _LG_DC_ */
    
#ifdef  _LG_FONT_
    #ifndef  FONT_NAME_LEN
        #define  FONT_NAME_LEN                                  8
    #endif  /* FONT_NAME_LEN */

    #if  (FONT_NAME_LEN<3)?1:0
        #undef   FONT_NAME_LEN
        #define  FONT_NAME_LEN                                  3
    #endif

    #ifndef  MISSING_CHAR_BLANK_WIDTH
        #define  MISSING_CHAR_BLANK_WIDTH                       8
    #endif  /* MISSING_CHAR_BLANK_WIDTH */

    #if  (MISSING_CHAR_BLANK_WIDTH<4)?1:0
        #undef   MISSING_CHAR_BLANK_WIDTH
        #define  MISSING_CHAR_BLANK_WIDTH                       4
    #endif
#endif  /* _LG_FONT_ */

#ifdef  _LG_MULTI_BYTE_CODE_VERSION_
    #ifndef  MULTI_BYTE_START_CODE
        #define MULTI_BYTE_START_CODE                   0xA1
    #endif  /* MULTI_BYTE_START_CODE */
#endif  /* _LG_MULTI_BYTE_CODE_VERSION_ */


#ifndef  _LG_BITMAP_
    #undef  _LG_1_BIT_BITMAP_
    #undef  _LG_2_BIT_BITMAP_
    #undef  _LG_4_BIT_BITMAP_
    #undef  _LG_8_BIT_BITMAP_
    #undef  _LG_16_BIT_BITMAP_
    #undef  _LG_24_BIT_BITMAP_
    #undef  _LG_32_BIT_BITMAP_
    #undef  _LG_FILL_BITMAP_EXTENSION_
#endif  /* _LG_BITMAP_ */
    
#ifndef  _LG_1_BIT_BITMAP_
    #ifndef  _LG_2_BIT_BITMAP_
        #ifndef  _LG_4_BIT_BITMAP_
            #ifndef  _LG_8_BIT_BITMAP_
                #ifndef  _LG_16_BIT_BITMAP_
                    #ifndef  _LG_24_BIT_BITMAP_
                        #ifndef  _LG_32_BIT_BITMAP_
                            #undef  _LG_BITMAP_
                        #endif  /* _LG_32_BIT_BITMAP_ */ 
                    #endif  /* _LG_24_BIT_BITMAP_ */ 
                #endif  /* _LG_16_BIT_BITMAP_ */ 
            #endif  /* _LG_8_BIT_BITMAP_ */ 
        #endif  /* _LG_4_BIT_BITMAP_ */ 
    #endif  /* _LG_2_BIT_BITMAP_ */ 
#endif  /* _LG_1_BIT_BITMAP_ */ 

#ifndef  _LG_ICON_
    #undef  _LG_1_BIT_ICON_
    #undef  _LG_2_BIT_ICON_
    #undef  _LG_4_BIT_ICON_
    #undef  _LG_8_BIT_ICON_
    #undef  _LG_16_BIT_ICON_
    #undef  _LG_24_BIT_ICON_
    #undef  _LG_32_BIT_ICON_
    #undef  _LG_FILL_ICON_EXTENSION_
#endif  /* _LG_ICON_ */

#ifndef  _LG_1_BIT_ICON_
    #ifndef  _LG_2_BIT_ICON_
        #ifndef  _LG_4_BIT_ICON_
            #ifndef  _LG_8_BIT_ICON_
                #ifndef  _LG_16_BIT_ICON_
                    #ifndef  _LG_24_BIT_ICON_
                        #ifndef  _LG_32_BIT_ICON_
                            #undef  _LG_ICON_
                        #endif  /* _LG_32_BIT_ICON_ */ 
                    #endif  /* _LG_24_BIT_ICON_ */ 
                #endif  /* _LG_16_BIT_ICON_ */ 
            #endif  /* _LG_8_BIT_ICON_ */ 
        #endif  /* _LG_4_BIT_ICON_ */ 
    #endif  /* _LG_2_BIT_ICON_ */ 
#endif  /* _LG_1_BIT_ICON_ */ 

#ifndef  _LG_GIF_
    #undef  _LG_1_BIT_GIF_
    #undef  _LG_2_BIT_GIF_
    #undef  _LG_4_BIT_GIF_
    #undef  _LG_8_BIT_GIF_
#endif  /* _LG_GIF_ */

#ifndef  _LG_1_BIT_GIF_
    #ifndef  _LG_2_BIT_GIF_
        #ifndef  _LG_4_BIT_GIF_
            #ifndef  _LG_8_BIT_GIF_
                #undef  _LG_GIF_
            #endif  /* _LG_8_BIT_GIF_ */ 
        #endif  /* _LG_4_BIT_GIF_ */ 
    #endif  /* _LG_2_BIT_GIF_ */ 
#endif  /* _LG_1_BIT_GIF_ */ 


/* Screen support macro */
#ifndef  _LG_SCREEN_
    #undef  _LG_NEED_REFRESH_SCREEN_
    #undef  _LG_SNAPSHOT_
#endif  /* _LG_SCREEN_ */


/* MTJT support macro */
#ifndef  _LG_MTJT_
    #undef  _LG_CURSOR_ 
#endif  /* _LG_MTJT_ */


/* Message support macro */
#ifndef  _LG_MESSAGE_
    #undef  _LG_LONG_MESSAGE_
    #undef  _LG_COUNTER_
    #undef  _LG_TIMER_
#endif  /* _LG_MESSAGE_ */

#ifdef  _LG_MESSAGE_
    #ifndef  MESSAGE_QUEUE_LEN
        #define  MESSAGE_QUEUE_LEN                              8
    #endif  /* MESSAGE_QUEUE_LEN */
    #if  (MESSAGE_QUEUE_LEN<8)?1:0
        #undef   MESSAGE_QUEUE_LEN 
        #define  MESSAGE_QUEUE_LEN                             8
    #endif
#endif  /* _LG_MESSAGE_ */

#ifdef  _LG_COUNTER_
    #ifndef  MAX_COUNTER
        #define  MAX_COUNTER                                    4
    #endif  /* MAX_COUNTER */
    #if  (MAX_COUNTER<1)?1:0
        #undef   MAX_COUNTER 
        #define  MAX_COUNTER                                    1
    #endif
#endif  /* _LG_COUNTER_ */

#ifdef  _LG_TIMER_
    #ifndef  MAX_TIMER
        #define  MAX_TIMER                                      4
    #endif  /* MAX_TIMER */
    #if  (MAX_TIMER<1)?1:0
        #undef   MAX_TIMER 
        #define  MAX_TIMER                                      1
    #endif

    #ifndef TIMER_OFFSET
        #define  TIMER_OFFSET                                   75
    #endif  /* TIMER_OFFSET */
#endif  /* _LG_TIMER_ */


/* Rectangle route support macro */    


/* Function tools support macro */    
#ifndef  _LG_TOOLS_
    #undef  _LG_GB2312_TO_UNICODE_
    #undef  _LG_UNICODE_TO_GB2312_
    #undef  _LG_FAST_UNICODE_TO_GB2312_
#endif  /* _LG_TOOLS_ */
    
#ifndef  _LG_UNICODE_TO_GB2312_    
    #undef  _LG_FAST_UNICODE_TO_GB2312_
#endif  /* _LG_UNICODE_TO_GB2312_ */


/* Optization storage support macro */
#ifndef  GUI_VAR_CONST
    #define  GUI_VAR_CONST                              const
#endif  /* GUI_VAR_CONST */

#ifndef  GUI_DATA_CONST
    #define  GUI_DATA_CONST                             const
#endif  /* GUI_DATA_CONST */


#endif   /* __LGUI_DEP_CNF_BASIC_HEADER__ */
