/*   
 *  Copyright (C) 2011- 2018 Rao Youkun(960747373@qq.com)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 */

/*
 * Do not edit this file
 */
#ifndef  __LGUI_DEP_CNF_WIN_HEADER__
#define  __LGUI_DEP_CNF_WIN_HEADER__        1


#define  _LG_WINDOW_BAR_


#endif   /* __LGUI_DEP_CNF_WIN_HEADER__ */
