#!/bin/bash
set -e

IMAGE_FILE=$1
ROM_DIR=$2
DISK_SIZE=$3
MOUNT_POINT=/tmp/mpoint
if [[ $# -ne 3 ]]; then
    echo ERR
    exit 1
fi

if [[ -z $IMAGE_FILE ]]; then
    echo ERR
    exit 1
fi
if [[ ! -d "$ROM_DIR" ]];then
    echo $ROM_DIR: not found!
    exit 1
fi

echo $ 1 $2 $3
rm $IMAGE_FILE -f
dd if=/dev/zero of=$IMAGE_FILE bs=1M count=$DISK_SIZE
mkfs.vfat $IMAGE_FILE
mkdir -p ${MOUNT_POINT}
sudo mount -t vfat -o loop,rw $IMAGE_FILE ${MOUNT_POINT}
sudo cp ${ROM_DIR}/* ${MOUNT_POINT}/ -rf
sync
sudo umount -f ${MOUNT_POINT}
rm ${MOUNT_POINT}/ -rf