#ifndef _SRV_FILE_SRV_H
#define _SRV_FILE_SRV_H

/* file server call */
enum filesrv_call_num {
    FILESRV_OPEN = 0,
    FILESRV_CLOSE,
    FILESRV_READ,
    FILESRV_WRITE,
    FILESRV_LSEEK,
    FILESRV_ASSERT,
    FILESRV_OPENDIR,
    FILESRV_CLOSEDIR,
    FILESRV_READDIR,
    FILESRV_REWINDDIR,
    FILESRV_MKDIR,
    FILESRV_UNLINK,
    FILESRV_RMDIR,
    FILESRV_RENAME,
    FILESRV_FTRUNCATE,
    FILESRV_FSYNC,
    FILESRV_STAT,
    FILESRV_CHMOD,
    FILESRV_FCHMOD,
    FILESRV_UTIME,
    FILESRV_FEOF,
    FILESRV_FERROR,
    FILESRV_FTELL,
    FILESRV_FSIZE,
    FILESRV_REWIND,
    FILESRV_MOUNT,
    FILESRV_UNMOUNT,
    FILESRV_MKFS,
    FILESRV_CHDIR,
    FILESRV_CALL_NR,    /* 最大数量 */
};
/* 缓冲区最大长度 */
#define FILESRV_BUF_MAX_SIZE    (128*1024)


#define MAX_PATH_LEN    260


#endif   /* _SRV_FILE_SRV_H */