X_INCDIRS	:= xlibc/include lvgl/

SRC			+= src/lv_core/
SRC			+= src/lv_draw/ 
SRC			+= src/lv_font/ 
SRC			+= src/lv_gpu/ 
SRC			+= src/lv_hal/ 
SRC			+= src/lv_misc/ 
SRC			+= src/lv_themes/
SRC			+= src/lv_widgets/

TARGET_TYPE	:= static
NAME		:= lvgl
