sinclude ../scripts/env.mk
sinclude ../scripts/localenv.mk

X_ASFLAGS	:= $(ENV_AFLAGS)
X_CFLAGS	:= $(ENV_CFLAGS)

X_LDFLAGS	:= $(ENV_LDFLAGS)

LD			:=  $(ENV_LD)
AS			:= $(ENV_AS)
export AS LD

#MODULE		:= xlibc
MODULE		+= xcrt
#MODULE		+= xlibcpp
#MODULE		+= sconf
#MODULE		+= pthread
#MODULE		+= uview
