/*
 * Copyright (c) 2012  Rao Youkun(raoyoukun@aliyun.com)
 * LguiTool.exe is free program. You can copy or redistribute it freely
 *
 * Created by LguiTool.exe(Version 1.0.0).
 * Converted at Thu Feb 22 15:21:49 2018
 *
 * QQ ID: 854992939. QQ Group ID: 317305416
 *
 * Do not edit this file!
 */

#ifndef  __LGUI_LAKE_ALPHA_BITMAP_HEADER__
#define  __LGUI_LAKE_ALPHA_BITMAP_HEADER__


#include  <learninggui.h>


#ifdef  _LG_BITMAP_

#ifdef  __cplusplus
extern "C"
{
#endif  /* __cplusplus */


    extern  GUI_VAR_CONST  GUI_BITMAP  lake_alpha;


#ifdef  __cplusplus
}
#endif  /* __cplusplus */

#endif  /* _LG_BITMAP_ */

#endif  /* __LGUI_LAKE_ALPHA_BITMAP_HEADER__ */
