/*
 * Copyright (c) 2017  Rao Youkun(760747373@qq.com)
 * LguiTool.exe is free program. You can copy or redistribute it freely
 *
 * Created by LguiTool.exe(Version 1.0.0).
 * Converted at Tue Sep 26 09:51:13 2017
 *
 * QQ ID: 760747373. QQ Group ID: 275782855
 *
 * Do not edit this file!
 */

#ifndef  __LGUI_ZHUHAI_BITMAP_HEADER__
#define  __LGUI_ZHUHAI_BITMAP_HEADER__

#include  <learninggui.h>

#ifdef  _LG_BITMAP_

#ifdef  __cplusplus
extern "C"
{
#endif

    extern  GUI_VAR_CONST  GUI_BITMAP  zhuhai;

#ifdef  __cplusplus
}
#endif

#endif  /* _LG_BITMAP_ */

#endif  /* __LGUI_ZHUHAI_BITMAP_HEADER__ */
