# 文件路径
TEST 		= ./test
INFONES 	= ./infones
TERMINAL 	= ./terminal

.PHONY: all clean

all: 
	cd $(TEST) && make
	cd $(INFONES) && make
	cd $(TERMINAL) && make
	
clean:
	cd $(TEST) && make clean
	cd $(INFONES) && make clean
	cd $(TERMINAL) && make clean
	